# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: MSBuild@1
  inputs:
    solution: 'Alba/WpfUI/WpfUI.csproj'
    msbuildArguments: '/Target:Restore'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'TerritoryTools.pfx'

- task: CopyFiles@2
  inputs:
    Contents: 'TerritoryTools.pfx'
    TargetFolder: '$(Build.SourcesDirectory)/Alba/WpfUI'

- task: MSBuild@1
  inputs:
    solution: 'Alba/WpfUI/WpfUI.csproj'
    msbuildArguments: '/Target:Build /p:Configuration=Release'

- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)/Alba/WpfUI/Publish.ps1'
    workingDirectory: '$(Build.SourcesDirectory)/Alba/WpfUI'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/Alba/WpfUI/Publish'
    artifact: 'ClickOncePublish'
    publishLocation: 'pipeline'

