version: '3.5'

services:  
  urls:
    container_name: url-shortener
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./UrlShortener/Dockerfile
    networks:
      - main
    ports:
      - "5010:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - UrlShortenerDbConnectionString=$ConnectionStrings_UrlShortenerDb

networks:
  main:
    name: main-network